routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('_root_');


//Routes for Admin
// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');


// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::get('pages/photodelete/{page}', 'PageController@photodelete')->name('pages.photodelete');

    Route::resource('blogs', 'BlogController');
    Route::get('blogs/showhide/{blog}', 'BlogController@showhide')->name('blogs.showhide');
    Route::get('blogs/photodelete/{blog}', 'BlogController@photodelete')->name('blogs.photodelete');

    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('videos', 'VideoController');
    Route::get('videos/showhide/{video}', 'VideoController@showhide')->name('videos.showhide');
    Route::resource('fbvideos', 'FbvideoController');
    Route::get('fbvideos/showhide/{fbvideo}', 'FbvideoController@showhide')->name('fbvideos.showhide');
    Route::resource('albums','AlbumController');
    Route::post('albums/photodelete', 'AlbumController@photodelete')->name('albums.photodelete');

    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::post('logo', 'SettingController@logoChange')->name('change.logo');
    Route::post('headerbg', 'SettingController@headerbgChange')->name('change.headerbg');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');

    Route::resource('memberships', 'MembershipController');
    Route::get('memberships/showhide/{membership}', 'MembershipController@showhide')->name('memberships.showhide');
    Route::get('memberships/photodelete/{membership}', 'MembershipController@photodelete')->name('memberships.photodelete');

    Route::get('membershipjoin-request','MembershipRequestController@index')->name('membershipjoin.request');
    Route::get('membershipjoin-request/{id}','MembershipRequestController@view')->name('membershipjoin.request.view');
    Route::post('membershipjoin-request/{id}/approve', 'MembershipRequestController@approve')->name('membershipjoin.request.approve');
    Route::post('membershipjoin-request/{id}/decline', 'MembershipRequestController@decline')->name('membershipjoin.request.decline');

    Route::resource('socials', 'SocialController');
    Route::get('partners/photodelete/{partner}', 'PartnerController@photodelete')->name('partners.photodelete');
    Route::resource('partners', 'PartnerController');
    Route::resource('admins', 'AdminController');

    Route::resource('categories', 'CategoryController');
    Route::post('categories/order', 'CategoryController@order')->name('categories.order');
    Route::resource('items', 'ItemController');
    Route::post('items/order', 'ItemController@order')->name('items.order');

    Route::resource('employees', 'EmployeeController');
    Route::get('employees/showhide/{employee}', 'EmployeeController@showhide')->name('employees.showhide');
    Route::get('employees/showhidepage/{employee}', 'EmployeeController@showhidepage')->name('employees.showhidepage');
    Route::get('employees/photodelete/{employee}', 'EmployeeController@photodelete')->name('employees.photodelete');

    Route::resource('appointments', 'AppointmentController');
    Route::post('appointment/{id}/paid', 'AppointmentController@approve')->name('appointment.paid.approve');


    Route::get('password/change', 'DashboardController@passwordchange')->name('password.change');
    Route::get('activity', 'AdminController@activity')->name('admin.activity');
    Route::post('password/change', 'DashboardController@passwordstore');

});


$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if($page->slug == 'contact'){
        $router->get($page->slug, 'PageController@contact')->name('contact');
    }elseif($page->slug == 'about-us')
    {
        $router->get($page->slug,'PageController@aboutus');
    } elseif($page->slug == 'our-team')
    {
        $router->get($page->slug,'PageController@ourteam');
    } elseif($page->slug == 'testimonials')
    {
        $router->get($page->slug,'PageController@review');
    }elseif($page->slug == 'blog')
    {
        $router->get($page->slug,'PageController@blog')->name('blogs.main');
    }
    elseif($page->slug == 'single-blog')
    {
        $router->get($page->slug.'/{blog}','PageController@singleblog')->name('singleblog');
    }
    elseif($page->slug == 'photo-gallery')
    {
        $router->get($page->slug,'PageController@photogallery')->name('photod');
    }elseif($page->slug == 'video-gallery')
    {
        $router->get($page->slug,'PageController@videogallery')->name('videod');
    }elseif($page->slug == 'membership')
    {
        $router->get($page->slug,'PageController@membership');
    }elseif($page->slug == 'thank-you')
    {
        $router->get($page->slug,'PageController@thankyou')->name('thankyou');
    }elseif($page->slug == 'appointment')
    {
        $router->get($page->slug,'AppointmentController@appointment')->name('appointment');
    }
    elseif($page->slug <> '/'){
        $router->get($page->slug, 'PageController@index');
    }
}

Auth::routes();

Route::get('captcha/image/jpg', 'CaptchaController@imagejpg')->name('captcha_img');
Route::post('contactmail', 'PageController@contactmail')->name('contactmail');



Route::group(['middlewareGroups' => 'web'], function () {

    Route::post('reviewstore', 'PageController@reviewsave')->name('reviewstore');
    Route::get('service','PageController@service')->name('service.main');
    Route::get('membership/{id}','PageController@membershipdetails')->name('membership.details');
    Route::post('membership/checkout','PageController@membershipcheckout')->name('membership.checkout');
    Route::post('dynamic_dependent/fetch/item',[
        'as'=>'dynamindependent.fetch_item','uses'=>'AppointmentController@fetchitem'
    ]);
    Route::post('dynamic_dependent/fetch/employee',[
        'as'=>'dynamindependent.fetch_employee','uses'=>'AppointmentController@fetchemployee'
    ]);
    Route::post('appointment_dates_load','AppointmentController@appointment_dates_load')->name('appointment_dates_load');
    Route::post('appointment_time_load','AppointmentController@appointment_time_load')->name('appointment_time_load');

    Route::post('appointment_next_load','AppointmentController@appointment_next_load')->name('appointment_next_load');
    Route::post('appointment/book','AppointmentController@appointment_book')->name('appointment_book');
    Route::get('checkout/complete','AppointmentController@complete')->name('checkout.complete');

//    Route::get('blogs/{blog}', 'PageController@singleblog')->name('singleblog');
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('profile', 'UserController@profile')->name('user.profile');
    Route::post('changepassword', 'UserController@changepassword')->name('changepassword');
});

Route::fallback(function(){
    return response()->view('errors.404', [], 404);
})->name('fallback');


Route::get('/appointmentservice','AppointmentController@storeCostDetails')->name('appointmentService');

resources/views/admin/page/create.blade.php
@extends('admin.app')

@section('title')
Add Page
@endsection

@section('content')

<h3 class="page-title">Add Page <a href="{{ route('pages.index') }}" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> <span>Back</span></a></h3>

<hr>

<div class="panel">
	<div class="panel-body">
		<form class="form-horizontal" action="{{ route('pages.store') }}" accept-charset="utf-8" method="post" enctype="multipart/form-data">
			{!! csrf_field() !!}

			@include('admin.page.form')
			<div class="form-group">
				<label class="col-sm-2 control-label">&nbsp;</label>
				<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
			</div>	
		</form>
	</div>
</div>
@endsection

resources/views/admin/page/edit.blade.php
@extends('admin.app')

@section('title')
Edit Page
@endsection

@section('content')
<h3 class="page-title">Edit Page <a href="{{ route('pages.index') }}" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> <span>Back</span></a></h3>

<hr>

<div class="panel">
	<div class="panel-body">
		<form class="form-horizontal" action="{{ route('pages.update', $page->id) }}" accept-charset="utf-8" method="post" enctype="multipart/form-data">
			{{ method_field('PUT') }}
			{!! csrf_field() !!}

			@include('admin.page.form')
			
			<div class="form-group">
				<label class="col-sm-2 control-label">&nbsp;</label>
				<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
			</div>	
		</form>
	</div>
</div>
@endsection

resources/views/admin/page/form.blade.php
<div class="form-group">
	<label class="col-sm-2 control-label" for="parent_id">Parent</label>
	<div class="col-sm-3">
		<select class="form-control" name="parent_id" id="parent_id">
			<option value="0">None</option>
			@foreach ($parents as $parent)
			<option value="{{ $parent->id }}" {{ $parent->id == old('parent_id', isset($page) ? $page->parent_id : null ) ? 'selected="selected"' : null }}>{{ $parent->title }}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="form-group">
	<label class="col-sm-2 control-label" for="title">Title</label>
	<div class="col-sm-4">
		<input class="col-md-4 form-control" placeholder="Title" name="title" value="{{ old('title', isset($page) ? $page->title : null) }}" type="text" id="title">
	</div>

	{{-- <label class="col-sm-2 control-label" for="slug">Alias</label>
	<div class="col-sm-4">
		<input class="col-md-4 form-control" placeholder="Alias" name="slug" value="{{ old('slug', isset($page) ? $page->slug : null) }}" type="text" id="slug">
	</div> --}}
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="position">Position</label>
	<div class="col-sm-3">
		<select class="form-control" name="position" id="position">
			<option value="0" {{ old('position', isset($page) ? $page->position : '') == 0 ? 'selected="selected"' : null }}>None</option>
			<option value="1" {{ old('position', isset($page) ? $page->position : '') == 1 ? 'selected="selected"' :  null}}>Top</option>
			<option value="2" {{ old('position', isset($page) ? $page->position : '' ) == 2 ? 'selected="selected"' : null }}>Footer</option>
			<option value="3" {{ old('position', isset($page) ? $page->position : '' ) == 3 ? 'selected="selected"' : null }}>Both</option>
		</select>
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="details">Details</label>
	<div class="col-sm-10">
		<textarea class="col-md-8 form-control" rows="8" placeholder="Details" name="details" id="details">{{ old('details', isset($page) ? $page->details : null) }}</textarea>
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="image">Image [1170*410]</label>
	<div class="col-sm-10">
		@if(isset($page) && $page->image)
			<img src="{{asset('/uploads/pages/'.$page->image)}}" width="160" height="100">
			<a href="{{route('pages.photodelete',$page->id)}}" class="btn btn-danger">Delete this image</a>
		@endif
		<input type="file" name="image" id="image">
	</div>
</div>

<div class="form-group">
	<label class="col-sm-2 control-label" for="meta_title">Meta title</label>
	<div class="col-sm-10">
		<textarea class="col-md-8 form-control" rows="4" placeholder="Meta title" name="meta_title" id="meta_title">{{ old('meta_title', isset($page) ? $page->meta_title : null) }}</textarea>
	</div>
</div>
<div class="form-group">
	<label class="col-sm-2 control-label" for="meta_description">Meta description</label>
	<div class="col-sm-10">
		<textarea class="col-md-8 form-control" rows="4" placeholder="Meta description" name="meta_description" id="meta_description">{{ old('meta_description', isset($page) ? $page->meta_description : null) }}</textarea>
	</div>

</div>
<div class="form-group">
	<label class="col-sm-2 control-label" for="meta_keyword">Meta keyword</label>
	<div class="col-sm-10">
		<textarea class="col-md-8 form-control" rows="4" placeholder="Meta keyword" name="meta_keyword" id="meta_keyword">{{ old('meta_keyword', isset($page) ? $page->meta_keyword : null) }}</textarea>
	</div>
</div>
<div class="form-group">
	<div class="col-sm-3 col-sm-offset-2">
		<div class="custom-control custom-checkbox mr-sm-2">
			<input type="checkbox" class="custom-control-input" id="status" name="status"  value="1" {{ old('status', isset($page) ? $page->status : 1) == 1 ? 'checked=checked' : null  }}>
			<label class="custom-control-label" for="status">Active</label>
		</div>
	</div>
</div>

resources/views/admin/page/index.blade.php
@extends('admin.app') 
@section('title') Pages
@endsection
 
@section('content')

<h3 class="page-title">Pages <a href="{{ route('pages.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <span>Add New</span></a></h3>

<div class="panel">
	<div class="panel-heading">
		<form class="form-horizontal">
			<div class="form-group">
				<div class="col-sm-3">
					<input type="text" class="form-control form-control-sm" name="keyword" placeholder="Keyword" value="{{ request()->keyword }}">
				</div>
				<div class="col-sm-2">
					{{-- <button type="submit" class="btn btn-primary"> Search </button> --}}
					<input type="submit" class="btn btn-primary" value="Search">
				</div>
				<label for="" class="col-sm-1 control-label">Filter</label>
				<div class="col-sm-3">
					<select name="filter" class="form-control" onchange="this.form.submit()">
						<option value="0">All</option>
						@foreach ($parents as $parent)
							@if ($parent->child()->count() > 0)
							<option {{ request()->filter == $parent->id ? 'selected=selected' : null }} value="{{ $parent->id }}">{{ $parent->title }}</option>							
							@endif
						@endforeach
						<option {{ request()->filter == 'main_menu' ? 'selected=selected' : null }} value="main_menu">Main Menu</option>
						<option {{ request()->filter == 'footer' ? 'selected=selected' : null }} value="footer">Footer</option>
					</select>
				</div>

				@if(request()->filter || request()->keyword)
				<div class="col-sm-3">
					<a href="{{ route('pages.index') }}" class="btn btn-danger pull-right">Clear filter</a>
				</div>
				@endif

			</div>
		</form>
	</div>
	<div class="panel-body">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Parent</th>
					<th>Title</th>
					<th>Url</th>
					<th>Status</th>
					<th>Created At</th>
					<th></th>
				</tr>
			</thead>
			<tbody id="sortable">
				@php $i=1; 
@endphp @foreach ($pages as $page)
				<tr id="{{ $page->id }}">
					<td>{{$i}}</td>
					<td>{{ $page->parent ? $page->parent->title : 'None' }}</td>
					<td>{{ str_limit($page->title,30) }}</td>
					<td>{{ $page->slug == '/' ? '/' : '/' . str_limit($page->slug,30) }}</td>
					<td>
						@if ($page->status)
							<a class="text-success" data-toggle="tooltip" data-placement="bottom" title="Click to hide" href="{{ route('pages.showhide', $page->id) }}">
								<i class="lnr lnr-checkmark-circle"></i>
								Active
							</a>
						@else
							<a class="text-danger" data-toggle="tooltip" data-placement="bottom" title="Click to show" href="{{ route('pages.showhide', $page->id) }}">
								<i class="lnr lnr-cross-circle"></i>
								Draft
							</a>
						@endif 
					</td>
					<td>{{ $page->created_at->format('M d, Y') }}</td>
					<td class="text-right">

						<a class="btn btn-primary btn-sm" href="{{ route('pages.edit', $page->id) }}"><i class="lnr lnr-pencil"></i></a>

						<div class="pull-right" style="margin-left: 10px;">
							<form onsubmit="return confirm('Are you sure?')" action="{{ route('pages.destroy', $page->id) }}" method="post">
								{{ method_field('DELETE') }} {{ csrf_field() }}
								<button type="submit" class="btn btn-danger btn-sm"><i class="lnr lnr-trash"></i></button>
							</form>
						</div>
					</td>
				</tr>
				@php $i++; 
@endphp @endforeach
			</tbody>
		</table>
	</div>
	<div class="panel-footer">{{ $pages->links() }}</div>
</div>
@endsection

 
@section('script') @if(request()->filter)
<script>
	$( function() {
		$( "#sortable" ).sortable({
			update: function (event, ui) {
				var data = $(this).sortable('toArray');
				url = "{{ route('pages.order') }}";
				$.ajax(url, {
					data: {
						'_token': "{{ csrf_token() }}",
						'order': "{{ (request()->filter == 'main_menu' ? 'menu_order' : (request()->filter == 'footer' ? 'footer_order' : 'order_by')) }}",
						'data':data
					},
					type: 'POST',
				});
			}
		});
	} );

</script>
@endif
@endsection