routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('_root_');


//Routes for Admin
// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');


// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::get('pages/photodelete/{page}', 'PageController@photodelete')->name('pages.photodelete');

    Route::resource('blogs', 'BlogController');
    Route::get('blogs/showhide/{blog}', 'BlogController@showhide')->name('blogs.showhide');
    Route::get('blogs/photodelete/{blog}', 'BlogController@photodelete')->name('blogs.photodelete');

    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('videos', 'VideoController');
    Route::get('videos/showhide/{video}', 'VideoController@showhide')->name('videos.showhide');
    Route::resource('fbvideos', 'FbvideoController');
    Route::get('fbvideos/showhide/{fbvideo}', 'FbvideoController@showhide')->name('fbvideos.showhide');
    Route::resource('albums','AlbumController');
    Route::post('albums/photodelete', 'AlbumController@photodelete')->name('albums.photodelete');

    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::post('logo', 'SettingController@logoChange')->name('change.logo');
    Route::post('headerbg', 'SettingController@headerbgChange')->name('change.headerbg');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');

    Route::resource('memberships', 'MembershipController');
    Route::get('memberships/showhide/{membership}', 'MembershipController@showhide')->name('memberships.showhide');
    Route::get('memberships/photodelete/{membership}', 'MembershipController@photodelete')->name('memberships.photodelete');

    Route::get('membershipjoin-request','MembershipRequestController@index')->name('membershipjoin.request');
    Route::get('membershipjoin-request/{id}','MembershipRequestController@view')->name('membershipjoin.request.view');
    Route::post('membershipjoin-request/{id}/approve', 'MembershipRequestController@approve')->name('membershipjoin.request.approve');
    Route::post('membershipjoin-request/{id}/decline', 'MembershipRequestController@decline')->name('membershipjoin.request.decline');

    Route::resource('socials', 'SocialController');
    Route::get('partners/photodelete/{partner}', 'PartnerController@photodelete')->name('partners.photodelete');
    Route::resource('partners', 'PartnerController');
    Route::resource('admins', 'AdminController');

    Route::resource('categories', 'CategoryController');
    Route::post('categories/order', 'CategoryController@order')->name('categories.order');
    Route::resource('items', 'ItemController');
    Route::post('items/order', 'ItemController@order')->name('items.order');

    Route::resource('employees', 'EmployeeController');
    Route::get('employees/showhide/{employee}', 'EmployeeController@showhide')->name('employees.showhide');
    Route::get('employees/showhidepage/{employee}', 'EmployeeController@showhidepage')->name('employees.showhidepage');
    Route::get('employees/photodelete/{employee}', 'EmployeeController@photodelete')->name('employees.photodelete');

    Route::resource('appointments', 'AppointmentController');
    Route::post('appointment/{id}/paid', 'AppointmentController@approve')->name('appointment.paid.approve');


    Route::get('password/change', 'DashboardController@passwordchange')->name('password.change');
    Route::get('activity', 'AdminController@activity')->name('admin.activity');
    Route::post('password/change', 'DashboardController@passwordstore');

});


$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if($page->slug == 'contact'){
        $router->get($page->slug, 'PageController@contact')->name('contact');
    }elseif($page->slug == 'about-us')
    {
        $router->get($page->slug,'PageController@aboutus');
    } elseif($page->slug == 'our-team')
    {
        $router->get($page->slug,'PageController@ourteam');
    } elseif($page->slug == 'testimonials')
    {
        $router->get($page->slug,'PageController@review');
    }elseif($page->slug == 'blog')
    {
        $router->get($page->slug,'PageController@blog')->name('blogs.main');
    }
    elseif($page->slug == 'single-blog')
    {
        $router->get($page->slug.'/{blog}','PageController@singleblog')->name('singleblog');
    }
    elseif($page->slug == 'photo-gallery')
    {
        $router->get($page->slug,'PageController@photogallery')->name('photod');
    }elseif($page->slug == 'video-gallery')
    {
        $router->get($page->slug,'PageController@videogallery')->name('videod');
    }elseif($page->slug == 'membership')
    {
        $router->get($page->slug,'PageController@membership');
    }elseif($page->slug == 'thank-you')
    {
        $router->get($page->slug,'PageController@thankyou')->name('thankyou');
    }elseif($page->slug == 'appointment')
    {
        $router->get($page->slug,'AppointmentController@appointment')->name('appointment');
    }
    elseif($page->slug <> '/'){
        $router->get($page->slug, 'PageController@index');
    }
}

Auth::routes();

Route::get('captcha/image/jpg', 'CaptchaController@imagejpg')->name('captcha_img');
Route::post('contactmail', 'PageController@contactmail')->name('contactmail');



Route::group(['middlewareGroups' => 'web'], function () {

    Route::post('reviewstore', 'PageController@reviewsave')->name('reviewstore');
    Route::get('service','PageController@service')->name('service.main');
    Route::get('membership/{id}','PageController@membershipdetails')->name('membership.details');
    Route::post('membership/checkout','PageController@membershipcheckout')->name('membership.checkout');
    Route::post('dynamic_dependent/fetch/item',[
        'as'=>'dynamindependent.fetch_item','uses'=>'AppointmentController@fetchitem'
    ]);
    Route::post('dynamic_dependent/fetch/employee',[
        'as'=>'dynamindependent.fetch_employee','uses'=>'AppointmentController@fetchemployee'
    ]);
    Route::post('appointment_dates_load','AppointmentController@appointment_dates_load')->name('appointment_dates_load');
    Route::post('appointment_time_load','AppointmentController@appointment_time_load')->name('appointment_time_load');

    Route::post('appointment_next_load','AppointmentController@appointment_next_load')->name('appointment_next_load');
    Route::post('appointment/book','AppointmentController@appointment_book')->name('appointment_book');
    Route::get('checkout/complete','AppointmentController@complete')->name('checkout.complete');

//    Route::get('blogs/{blog}', 'PageController@singleblog')->name('singleblog');
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('profile', 'UserController@profile')->name('user.profile');
    Route::post('changepassword', 'UserController@changepassword')->name('changepassword');
});

Route::fallback(function(){
    return response()->view('errors.404', [], 404);
})->name('fallback');


Route::get('/appointmentservice','AppointmentController@storeCostDetails')->name('appointmentService');

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@yield('title', 'Dashboard') || {{ config('app.name') }}</title>
    <link rel="stylesheet" href="{{ asset('vendor/jquery-ui/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/admin/icon/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/admin.css???') }}">
    <link rel="stylesheet" href="{{ asset('css/admin-responsive.css???') }}">
    <link rel="icon" href="{{ asset('images/admin/w3web.jpg') }}" type="image/x-icon" />

    <style media="screen">
        .bg-init,
        .animsition-overlay {
            background-color: #fff;
        }
    </style>

    <style type="text/css">
        table.table>tbody>tr>td {
            vertical-align: middle;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="background: #ccc;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                        class="icon-bar"></span> </button>
            <a class="navbar-brand hidden-xs" href="{{ route('admin.dashboard') }}" style="font-size: 16px;">Asmu Beautyparlor</a>
        </div>
        <div class="header_left">
            <img src="{{ App\Setting::getLogo() }}" alt="Asmu Beauty"
                 class="img-responsive" height="50" />
        </div>
        <ul class="header_right">
            {{-- <li class="user_image"><img src="{{ asset(config('cms.userimage')) }}" alt="" /></li> --}}
            <li class="name"><b>{{ Auth::user()->name }}</b></li>
            <li class="logout"><a href="{{ route('admin.logout') }}"> Logout <i class="lnr lnr-exit"></i></a></li>
            <li class="logout"><a href="{{ route('password.change') }}"> Password Change <i class="lnr lnr-lock"></i></a></li>
            <li class="logout"><a href="{{ route('admin.activity') }}"> Log <i class="lnr lnr-keyboard"></i></a></li>
            <li><a href="{{ route('settings.index') }}"><i class="lnr lnr-cog"></i> <span>Settings</span></a></li>
        </ul>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <div class="side-bar" id="side-bar">
                <ul>
                    <li><a href="{{ route('admin.dashboard') }}" {!!(!request()->segment(2) ? 'class="active"' : null) !!} ><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>

                    <li><a href="{{ route('pages.index') }}" {!!(request()->segment(2) == 'pages' ? 'class="active"' : null) !!}><i class="lnr lnr-file-empty"></i> <span>Pages</span></a></li>

                    <li><a href="{{ route('labels.index') }}" {!!(request()->segment(2) == 'labels' ? 'class="active"' : null) !!}><i class="lnr lnr-spell-check"></i> <span>Labels</span></a></li>

                    <li><a href="{{ route('categories.index') }}" {!!(request()->segment(2) == 'categories' ?'class="active"' : null) !!}><i class="lnr lnr-menu"></i> <span>Categories</span></a></li>

                    <li><a href="{{ route('items.index') }}" {!!(request()->segment(2) == 'items' ? 'class="active"' : null) !!}><i class="lnr lnr-store"></i> <span>Services</span></a></li>

                    <li><a href="{{ route('employees.index') }}" {!!(request()->segment(2) == 'employees' ? 'class="active"' : null) !!}><i class="lnr lnr-shirt"></i> <span>Employees</span></a></li>

                    <li><a href="{{ route('slides.index') }}" {!!(request()->segment(2) == 'slides' ? 'class="active"' : null) !!}><i class="lnr lnr-picture"></i> <span>Slides</span></a></li>

                    <li><a href="{{ route('reviews.index') }}" {!!(request()->segment(2) == 'reviews' ? 'class="active"' : null) !!}><i class="lnr lnr-bubble"></i> <span>Reviews</span></a></li>

                    <li><a href="{{ route('blogs.index') }}" {!!(request()->segment(2) == 'blogs' ? 'class="active"' : null) !!}><i class="lnr lnr-list"></i> <span>Blogs</span></a></li>

                    <li><a href="{{ route('memberships.index') }}" {!!(request()->segment(2) == 'memberships' ? 'class="active"' : null) !!}><i class="lnr lnr-file-add"></i> <span>Memberships</span></a></li>

                    <li><a href="{{ route('membershipjoin.request') }}" {!!(request()->segment(2) == 'membershipjoin.request' ? 'class="active"' : null) !!}><i class="lnr lnr-download"></i> <span>Membership Requests</span></a></li>

                    <li><a href="{{ route('albums.index') }}" {!!(request()->segment(2) == 'albums' ? 'class="active"' : null) !!}><i class="lnr lnr-camera"></i> <span>Photo Album</span></a></li>

                    <li><a href="{{ route('videos.index') }}" {!!(request()->segment(2) == 'videos' ? 'class="active"' : null) !!}><i class="lnr lnr-camera-video"></i> <span>Videos</span></a></li>

                    <li><a href="{{ route('socials.index') }}" {!!(request()->segment(2) == 'socials' ? 'class="active"' : null) !!}><i class="lnr lnr-link"></i> <span>Socials</span></a></li>

                    <li><a href="{{ route('partners.index') }}" {!!(request()->segment(2) == 'partners' ? 'class="active"' : null) !!}><i class="lnr lnr-flag"></i> <span>Partners</span></a></li>

                    <li><a href="{{ route('admins.index') }}" {!!(request()->segment(2) == 'admins' ? 'class="active"' : null) !!}><i class="lnr lnr-user"></i> <span>Admins</span></a></li>

                </ul>
            </div>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<div class="content">

    {{--<h1>@yield('title', 'Dashboard')</h1>--}}

    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if(Session::has('success'))
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <p>
                {{ Session::get('success') }}
            </p>
        </div>
    @endif
    @if(Session::has('error'))
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <p>
                {{ Session::get( 'error') }}
            </p>
        </div>
    @endif

    @yield('content')

</div>

<div class="footer">
    <p>2013 -
        <?php echo date("Y");?>, &copy; & Power by: <a href="https://w3web.co.uk/" target="_blank">W3 Web Technology</a></p>
</div>


<div class="modal fade" id="jsModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

<script src="{{ asset('vendor/jquery-ui/external/jquery/jquery.js') }}"></script>
<script src="{{ asset('vendor/jquery-ui/jquery-ui.min.js') }}"></script>
<script src="{{ asset('vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/enscroll.min.js') }}"></script>
<script src="{{ asset('js/admin.js??') }}"></script>
<script src="{{ asset('/vendor/ckeditor/ckeditor.js?ref_' . str_random()) }}"></script>
<script>
    CKEDITOR.replace('details', {
        height: 500,
        extraPlugins: 'autoembed,embed,image2',
        embed_provider: '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}',
        // embed_provider: '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}',
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&responseType=json&_token=' +
        '{{ csrf_token() }}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&responseType=json&_token=' + '{{ csrf_token() }}'
    });
</script>

<script>
    $(function () {
        $('.topbar').dropdown();
    });
    $(function () {
        $(".datepicker").datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'yy-mm-dd'
        });
    });
</script>

@yield('script')
</body>

</html>

resources/views/admin/changepassword.blade.php
@extends('admin.app') 
@section('title') Change Password
@endsection
 
@section('content')
<h3 class="page-title">Change Password</h3>

<div class="row">
	<div class="col-sm-12">
        <div class="panel panel-headline">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-lock fa-fw"></span> Change Password</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="POST" action="{{ route('password.change') }}">
                    {{ csrf_field() }}

                    <div class="form-group{{ $errors->has('old_password') ? ' has-error' : '' }}">
                        <label for="old_password" class="col-md-4 control-label">Password</label>

                        <div class="col-md-6">
                            <input id="old_password" type="password" class="form-control" name="old_password" required>

                            @if ($errors->has('old_password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('old_password') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">New Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                    <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                        <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>
                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>

                            @if ($errors->has('password_confirmation'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password_confirmation') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button type="submit" class="btn btn-primary">
                                Change Password
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('admin.app') 
@section('title') Dashboard
@endsection
 
@section('content')
<h3 class="page-title">Dashboard</h3>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-headline" style="border: 1px solid #c6c6c6;">
            <div class="panel-heading" style="background: #f1f1f1;">
                <h3 class="panel-title" style="text-align: center; font-size:24px;"><span class="lnr lnr-users"></span>Today Made Membership Requests</h3>
                <p class="panel-subtitle" style="text-align: center; font-size:22px;">Date: {{date('d M, Y')}}</p>
            </div>
            <div class="panel-body">
                @if ($memberships->count() > 0)
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Membership Type</th>
                                <th>Applicant</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Address</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($memberships as $membership)
                                <tr>
                                    <td>{{$membership->membership->title}} </td>
                                    <td>{{ $membership->name }}</td>
                                    <td>{{ $membership->email }}</td>
                                    <td>{{ $membership->phone }}</td>
                                    <td>{{ $membership->address }}</td>
                                    {{--<td><a href="" class="btn btn-primary btn-xs"><i class="lnr lnr-eye"></i></a></td>--}}
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <p>Records not found</p>
                @endif

            </div>

            <div class="panel-footer">
                <a href="{{route('membershipjoin.request')}}" class="btn btn-primary">View all</a>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-headline" style="border: 1px solid #c6c6c6;">
            <div class="panel-heading" style="background: #f1f1f1;">
                <h3 class="panel-title" style="text-align: center; font-size:24px;"><span class="lnr lnr-users"></span>Today Made Appointments</h3>
                <p class="panel-subtitle" style="text-align: center; font-size:22px;">Date: {{date('d M, Y')}}</p>
            </div>
            <div class="panel-body">
                @if ($appointments->count() > 0)
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#app.Id</th>
                                <th>Payment</th>
                                <th>Name</th>
                                <th>Phone</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($appointments as $appointment)
                                <tr>
                                    <td><a href="{{ route('appointments.show', $appointment->id) }}">#{{$appointment->id}}</a></td>
                                    <td>{{$appointment->payment}}({!!$appointment->paid? '<span class="text-success">Paid</span>' : '<span class="text-danger">Unpaid</span>'!!})

                                    </td>
                                    <td>{{ $appointment->name }}</td>
                                    <td>{{ $appointment->phone }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <p>Records not found</p>
                @endif

            </div>

            <div class="panel-footer">
                <a href="{{ route('appointments.index') }}" class="btn btn-primary">View all</a>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-headline">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-users fa-fw"></span>Active Users</h3>
                {{--
                <p class="panel-subtitle">Date: {{date('d M, y')}}</p> --}}
            </div>
            <div class="panel-body">

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Type</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($user_details as $user)

                                <tr>
                                    <td>{{$user->id}}</td>
                                    @if($user->groups == 100)
                                      <td>Admin</td>
                                    @else
                                        <td>User</td>
                                    @endif
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>
                                        <ul class="online-status">
                                            @if($user->isOnline())
                                            <li class="active-status">Online</li>
                                            @else
                                                <li class="offline-status">Offline</li>
                                            @endif
                                        </ul>
                                    </td>
                                </tr>


                        @endforeach
                        </tbody>
                    </table>
                </div>


            </div>

        </div>
    </div>
</div>
@endsection

resources/views/admin/useractivity.blade.php
@extends('admin.app')

@section('title')
    Admin Log
@endsection

@section('content')




    <h3 class="page-title">Activity of {{$loged->user->name}}</h3>

    <div class="panel">
        <div class="panel-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Login Date Time</th>
                    <th>Ip Address</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach ($logs as $log)
                    <tr>
                        <td>{{ $log->login_time->format('M d, Y h:i:s A')}}</td>
                        <td>{{ $log->user_ip }}</td>
                        <td></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

        <div class="panel-footer">{{ $logs->links() }}</div>
    </div>
@endsection