routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@home')->name('_root_');


//Routes for Admin
// routes for admin
Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');
Route::post('admin/logout', 'Admin\LoginController@logout');


// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'namespace' => 'Admin'], function(){
    Route::get('/', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/phpinfo', 'DashboardController@phpinfo');
    Route::resource('pages', 'PageController');
    Route::post('pages/order', 'PageController@order')->name('pages.order');
    Route::get('pages/showhide/{page}', 'PageController@showhide')->name('pages.showhide');
    Route::get('pages/photodelete/{page}', 'PageController@photodelete')->name('pages.photodelete');

    Route::resource('blogs', 'BlogController');
    Route::get('blogs/showhide/{blog}', 'BlogController@showhide')->name('blogs.showhide');
    Route::get('blogs/photodelete/{blog}', 'BlogController@photodelete')->name('blogs.photodelete');

    Route::resource('slides', 'SlideController');
    Route::post('slides/order', 'SlideController@order')->name('slides.order');
    Route::get('slides/showhide/{slide}', 'SlideController@showhide')->name('slides.showhide');
    Route::resource('videos', 'VideoController');
    Route::get('videos/showhide/{video}', 'VideoController@showhide')->name('videos.showhide');
    Route::resource('fbvideos', 'FbvideoController');
    Route::get('fbvideos/showhide/{fbvideo}', 'FbvideoController@showhide')->name('fbvideos.showhide');
    Route::resource('albums','AlbumController');
    Route::post('albums/photodelete', 'AlbumController@photodelete')->name('albums.photodelete');

    Route::resource('labels', 'LabelController');
    Route::resource('settings', 'SettingController');
    Route::post('logo', 'SettingController@logoChange')->name('change.logo');
    Route::post('headerbg', 'SettingController@headerbgChange')->name('change.headerbg');
    Route::resource('reviews', 'ReviewController');
    Route::get('reviews/approve/{review}', 'ReviewController@approve')->name('reviews.approve');
    Route::get('reviews/cancel/{review}', 'ReviewController@cancel')->name('reviews.cancel');

    Route::resource('memberships', 'MembershipController');
    Route::get('memberships/showhide/{membership}', 'MembershipController@showhide')->name('memberships.showhide');
    Route::get('memberships/photodelete/{membership}', 'MembershipController@photodelete')->name('memberships.photodelete');

    Route::get('membershipjoin-request','MembershipRequestController@index')->name('membershipjoin.request');
    Route::get('membershipjoin-request/{id}','MembershipRequestController@view')->name('membershipjoin.request.view');
    Route::post('membershipjoin-request/{id}/approve', 'MembershipRequestController@approve')->name('membershipjoin.request.approve');
    Route::post('membershipjoin-request/{id}/decline', 'MembershipRequestController@decline')->name('membershipjoin.request.decline');

    Route::resource('socials', 'SocialController');
    Route::get('partners/photodelete/{partner}', 'PartnerController@photodelete')->name('partners.photodelete');
    Route::resource('partners', 'PartnerController');
    Route::resource('admins', 'AdminController');

    Route::resource('categories', 'CategoryController');
    Route::post('categories/order', 'CategoryController@order')->name('categories.order');
    Route::resource('items', 'ItemController');
    Route::post('items/order', 'ItemController@order')->name('items.order');

    Route::resource('employees', 'EmployeeController');
    Route::get('employees/showhide/{employee}', 'EmployeeController@showhide')->name('employees.showhide');
    Route::get('employees/showhidepage/{employee}', 'EmployeeController@showhidepage')->name('employees.showhidepage');
    Route::get('employees/photodelete/{employee}', 'EmployeeController@photodelete')->name('employees.photodelete');

    Route::resource('appointments', 'AppointmentController');
    Route::post('appointment/{id}/paid', 'AppointmentController@approve')->name('appointment.paid.approve');


    Route::get('password/change', 'DashboardController@passwordchange')->name('password.change');
    Route::get('activity', 'AdminController@activity')->name('admin.activity');
    Route::post('password/change', 'DashboardController@passwordstore');

});


$router = app()->make('router');
$pages = App\Page::all();
foreach ($pages as $page) {
    if($page->slug == 'contact'){
        $router->get($page->slug, 'PageController@contact')->name('contact');
    }elseif($page->slug == 'about-us')
    {
        $router->get($page->slug,'PageController@aboutus');
    } elseif($page->slug == 'our-team')
    {
        $router->get($page->slug,'PageController@ourteam');
    } elseif($page->slug == 'testimonials')
    {
        $router->get($page->slug,'PageController@review');
    }elseif($page->slug == 'blog')
    {
        $router->get($page->slug,'PageController@blog')->name('blogs.main');
    }
    elseif($page->slug == 'single-blog')
    {
        $router->get($page->slug.'/{blog}','PageController@singleblog')->name('singleblog');
    }
    elseif($page->slug == 'photo-gallery')
    {
        $router->get($page->slug,'PageController@photogallery')->name('photod');
    }elseif($page->slug == 'video-gallery')
    {
        $router->get($page->slug,'PageController@videogallery')->name('videod');
    }elseif($page->slug == 'membership')
    {
        $router->get($page->slug,'PageController@membership');
    }elseif($page->slug == 'thank-you')
    {
        $router->get($page->slug,'PageController@thankyou')->name('thankyou');
    }elseif($page->slug == 'appointment')
    {
        $router->get($page->slug,'AppointmentController@appointment')->name('appointment');
    }
    elseif($page->slug <> '/'){
        $router->get($page->slug, 'PageController@index');
    }
}

Auth::routes();

Route::get('captcha/image/jpg', 'CaptchaController@imagejpg')->name('captcha_img');
Route::post('contactmail', 'PageController@contactmail')->name('contactmail');



Route::group(['middlewareGroups' => 'web'], function () {

    Route::post('reviewstore', 'PageController@reviewsave')->name('reviewstore');
    Route::get('service','PageController@service')->name('service.main');
    Route::get('membership/{id}','PageController@membershipdetails')->name('membership.details');
    Route::post('membership/checkout','PageController@membershipcheckout')->name('membership.checkout');
    Route::post('dynamic_dependent/fetch/item',[
        'as'=>'dynamindependent.fetch_item','uses'=>'AppointmentController@fetchitem'
    ]);
    Route::post('dynamic_dependent/fetch/employee',[
        'as'=>'dynamindependent.fetch_employee','uses'=>'AppointmentController@fetchemployee'
    ]);
    Route::post('appointment_dates_load','AppointmentController@appointment_dates_load')->name('appointment_dates_load');
    Route::post('appointment_time_load','AppointmentController@appointment_time_load')->name('appointment_time_load');

    Route::post('appointment_next_load','AppointmentController@appointment_next_load')->name('appointment_next_load');
    Route::post('appointment/book','AppointmentController@appointment_book')->name('appointment_book');
    Route::get('checkout/complete','AppointmentController@complete')->name('checkout.complete');

//    Route::get('blogs/{blog}', 'PageController@singleblog')->name('singleblog');
});
Route::group(['middleware' => ['auth']], function(){
    Route::get('profile', 'UserController@profile')->name('user.profile');
    Route::post('changepassword', 'UserController@changepassword')->name('changepassword');
});

Route::fallback(function(){
    return response()->view('errors.404', [], 404);
})->name('fallback');


Route::get('/appointmentservice','AppointmentController@storeCostDetails')->name('appointmentService');

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
	public function scopeOfValue($query, $title)
	{
		$setting = $query->where('title', $title)->first();
		return $setting ? ($setting->value ? $setting->value : '&nbsp;') : $title;
	}


	public static function getLogo($default = 'images/logo.png')
	{
		$setting = Setting::whereTitle('logo')->first();
		if ($setting) {
			return asset('uploads/logo/' . $setting->value);
		} else {
			return asset($default);
		}
	}

	public static function getBg($default = 'images/bg_image_1920x1110.jpg')
	{
		$setting = Setting::whereTitle('header_bg')->first();
		if ($setting) {
			return asset('uploads/headerbg/' . $setting->value);
		} else {
			return asset($default);
		}
	}
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = Setting::latest()->paginate(10);
        $logos = Setting::where('title','logo')->get();
        $headerbgs = Setting::where('title','header_bg')->get();
        return view('admin.setting.index', compact('settings','logos','headerbgs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.setting.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|unique:settings',
            'value' => 'required'
        ]);

        $setting = new Setting;
        $setting->title = $request->title;
        $setting->value = $request->value;
        $setting->save();

        return redirect()->route('settings.index')->with('success', 'Setting added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function show(Setting $setting)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Setting $setting)
    {
        return view('admin.setting.edit', compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Setting $setting)
    {
        $this->validate($request, [
            'value' => 'required'
        ]);

        $setting->value = $request->value;
        $setting->save();

        return redirect()->route('settings.index')->with('success', 'Setting saved.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Setting  $setting
     * @return \Illuminate\Http\Response
     */
    public function destroy(Setting $setting)
    {
        if($setting){
            if($setting->value){
                $value = public_path('uploads/logo/' . $setting->value);
                $headerbg = public_path('uploads/headerbg/' . $setting->value);
                if(file_exists($value)){
                    unlink($value);
                }
                if(file_exists($headerbg)){
                    unlink($value);
                }
            }
            if($setting && $setting->delete()){
                return redirect()->route('settings.index')->with('success', 'Setting deleted.');
            }else{
                return redirect()->route('settings.index')->with('error', 'Error while deleting Setting.');
            }
        }
    else{
        abort();
    }

    }
    public function logoChange(Request $request)
    {
        if($request->hasFile('logo'))
        {
            $setting = Setting::whereTitle('logo')->first();
            if(!$setting)
            {
                $setting = new Setting;
            }

            if($setting->value && file_exists(public_path('uploads/logo/'.$setting->value))){
                unlink(public_path('uploads/logo/'.$setting->value));
            }

            $image_name = 'asmu-beauty-parlor-logo'.'.'.$request->logo->extension();
            $path = $request->logo->move('uploads/logo/', $image_name);
            $setting->title = 'logo';
            $setting->value = $image_name;
            $setting->save();
        }
        return redirect()->route('settings.index')->with('success','Logo Saved');
    }
    public function headerbgChange(Request $request)
    {
        if($request->hasFile('headerbg'))
        {
            $setting = Setting::whereTitle('header_bg')->first();
            if(!$setting)
            {
                $setting = new Setting;
            }

            if($setting->value && file_exists(public_path('uploads/headerbg/'.$setting->value))){
                unlink(public_path('uploads/headerbg/'.$setting->value));
            }

            $image_name = 'asmu-beauty-parlor-headerbg'.'.'.$request->headerbg->extension();
            $path = $request->headerbg->move('uploads/headerbg/', $image_name);
            $setting->title = 'header_bg';
            $setting->value = $image_name;
            $setting->save();
        }
        return redirect()->route('settings.index')->with('success','Page Header Background Saved');
    }
}

resources/views/admin/setting/create.blade.php
@extends('admin.app')

@section('title')
Add Setting
@endsection

@section('content')
<h3 class="page-title">Add Setting <a href="{{ route('settings.index') }}" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> <span>Back</span></a></h3>

<hr>

<div class="panel">
	<div class="panel-body">
		<form class="form-horizontal" action="{{ route('settings.store') }}" accept-charset="utf-8" method="post">
			{!! csrf_field() !!}

			@include('admin.setting.form')
			<div class="form-group">
				<label class="col-sm-2 control-label">&nbsp;</label>
				<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
			</div>	
		</form>
	</div>
</div>
@endsection

resources/views/admin/setting/edit.blade.php
@extends('admin.app')

@section('title')
Edit Setting
@endsection

@section('content')
<h3 class="page-title">Edit Setting <a href="{{ route('settings.index') }}" class="btn btn-primary pull-right"><i class="fa fa-arrow-left"></i> <span>Back</span></a></h3>

<hr>

<div class="panel">
	<div class="panel-body">
		<form class="form-horizontal" action="{{ route('settings.update', $setting->id) }}" accept-charset="utf-8" method="post">
			{{ method_field('PUT') }}
			{!! csrf_field() !!}

			@include('admin.setting.form')
			
			<div class="form-group">
				<label class="col-sm-2 control-label">&nbsp;</label>
				<div class="col-sm-10"><input class="btn btn-success" name="submit" value="Save" type="submit" id="form_submit"></div>		
			</div>	
		</form>
	</div>
</div>
@endsection

resources/views/admin/setting/form.blade.php
<div class="form-group">
	<label class="col-sm-2 control-label" for="title">Title</label>
	<div class="col-sm-6">
		<input class="col-md-4 form-control" placeholder="Title" name="title" value="{{ old('title', isset($setting) ? $setting->title : null) }}" type="text" id="title" {{ isset($setting) ? 'readonly="readonly"' : null }}>
	</div>
</div>


<div class="form-group">
	<label class="col-sm-2 control-label" for="value">Value</label>
	<div class="col-sm-8">
		<textarea rows="5" class="form-control" placeholder="Value" name="value" id="value">{{ old('value', isset($setting) ? $setting->value : null) }}</textarea>
	</div>
</div>

resources/views/admin/setting/index.blade.php
@extends('admin.app')

@section('title')
Settings
@endsection

@section('content')

	@if(count($logos) > 0)
		<h4>Logo</h4>
		@foreach($logos as $logo)
			<img src="{{ asset('uploads/logo/'.$logo->value) }}" height="100" width="150">
		@endforeach
		<form method="POST" action="{{ route('change.logo') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="logo-add">
				<input type="file" name="logo" onclick="myFunction()">
				<button type="submit" id="submit-btn" style="display: none;"> Submit</button>
			</div>
		</form>
	@else
		<img src="{{ asset('images/logo.png') }}" height="100" width="150">
		<form method="POST" action="{{ route('change.logo') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="logo-add">
				<input type="file" name="logo" onclick="myFunction()">
				<button type="submit" id="submit-btn" style="display: none;"> Submit</button>
			</div>
		</form>
	@endif
	<br>
	@if(count($headerbgs) > 0)
		<h4>Page Header Bg [current: 1920x1110]</h4>
		@foreach($headerbgs as $headerbg)
			<img src="{{ asset('uploads/headerbg/'.$headerbg->value) }}" height="100" width="150">
		@endforeach
		<form method="POST" action="{{ route('change.headerbg') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="logo-add">
				<input type="file" name="headerbg" onclick="myFunctions()">
				<button type="submit" id="submit-btns" style="display: none;"> Submit</button>
			</div>
		</form>
	@else
		<img src="{{ asset('images/bg_image_1920x1110.jpg') }}" height="100" width="150">
		<form method="POST" action="{{ route('change.headerbg') }}" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div class="logo-add">
				<input type="file" name="headerbg" onclick="myFunctions()">
				<button type="submit" id="submit-btns" style="display: none;"> Submit</button>
			</div>
		</form>
	@endif


	<h3 class="page-title">Settings <a href="{{ route('settings.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <span>Add New</span></a></h3>

<div class="panel">
	<div class="panel-body">
		<table class="table">
			<thead>
				<tr>
					<th>Title</th>
					<th>Value</th>
					<th>Created At</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach ($settings as $setting)
				<tr>
					<td>{{ $setting->title }}</td>
					<td>{{ $setting->value }}</td>
					<td>{{ $setting->created_at->format('M d, Y') }}</td>
					<td class="text-right">
						
							<a class="btn btn-primary btn-sm" href="{{ route('settings.edit', $setting->id) }}"><i class="lnr lnr-pencil"></i></a>

							<div class="pull-right" style="margin-left: 10px;"> 
								<form onsubmit="return confirm('Are you sure?')" action="{{ route('settings.destroy', $setting->id) }}" method="post">
									{{ method_field('DELETE') }}
									{{ csrf_field() }}		
									<button type="submit" class="btn btn-danger btn-sm"><i class="lnr lnr-trash"></i></button>
								</form>
							</div>
					</td>
				</tr>			
				@endforeach
			</tbody>
		</table>
	</div>

	<div class="panel-footer">{{ $settings->links() }}</div>
</div>
@endsection

@section('script')
	<script type="text/javascript">
//		logo
		function myFunction() {
			var x = document.getElementById("submit-btn");
			if (x.style.display === "none") {
				x.style.display = "block";
			} else {
				x.style.display = "none";
			}
		}
		//		Headerbg
		function myFunctions() {
			var x = document.getElementById("submit-btns");
			if (x.style.display === "none") {
				x.style.display = "block";
			} else {
				x.style.display = "none";
			}
		}
	</script>
@endsection